# fly.toml file generated for chachat on 2022-05-07T21:21:30+09:00

app = "chachat"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  PLATFORM_NAME = "fly.io"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "bin/rails db:migrate"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
