# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: chachat
    region: singapore
    plan: free
    env: ruby
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: chachat_redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: chachat_db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
    buildCommand: |
      bundle install
      bin/rails assets:precompile
      bin/rails db:migrate
    startCommand: bin/rails server -b 0.0.0.0
  - type: redis
    name: chachat_redis
    region: singapore
    ipAllowList: []
    plan: free

databases:
  - name: chachat_db
    region: singapore
    ipAllowList: []
